<?php 
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception; 
ob_start();
session_start();
include("connect.php");

/* Login Control */
if(isset($_POST['login'])){
	$user_mail = htmlspecialchars(trim($_POST['user_mail']));
	$user_pass = htmlspecialchars(trim(sha1(md5($_POST['user_pass']))));

	if($user_mail && $user_pass){
		$user_qry = $db->prepare("SELECT * FROM users WHERE user_mail=:mail AND user_pass=:pass");
		$user_qry->execute(array('mail' => $user_mail, 'pass' => $user_pass));
		$count = $user_qry->rowCount();

		if($count==1){
			$_SESSION['user_mail'] = $user_mail;
			header("Location:../home.php");
		}else{
			header("Location:../login.php?status=restrict");
		}
	}
}

/* Remember Password */
if(isset($_POST['repass'])){
	$remail = $_POST['remail'];
	if($remail){
		$user_qry = $db->prepare("SELECT * FROM users WHERE user_mail=:mail");
		$user_qry->execute(array('mail'=>$remail));
		$token=$user_qry->fetch(PDO::FETCH_ASSOC);
		$count = $user_qry->rowCount();

		if($count==1){
			$token_code = $token['user_token'];

            require '../phpmailer/Exception.php';
            require '../phpmailer/PHPMailer.php';
            require '../phpmailer/SMTP.php';

            $mail = new PHPMailer();
	
            $mail->isSMTP();
            $mail->Host = 'www.aldiahair.com';
            $mail->SMTPAuth = true;
            $mail->Username = 'no-reply@aldiahair.com'; //paste one generated by Mailtrap
            $mail->Password = 'AldiaHair2022'; //paste one generated by Mailtrap
            $mail->SMTPSecure = 'ssl';
            $mail->Port = 465;
            $mail->From     = "no-reply@aldiahair.com";
            $mail->Fromname = "Şifre Sıfırlama Talebi";
            $mail->CharSet = 'UTF-8';
            $mail->AddAddress($token['user_mail']);
            $mail->Subject  = "Şifre Sıfırlama Talebi";
            $mail->isHTML(true);
            $mail->Body = '<html>
                        <head>
                        <title>Şifre Sıfırlama</title>
                        </head>
                        <body>
							<img src="https://www.aldiahair.com/img/logo-dark.png" alt="logo">
                            <p style="font-weight: bold;">Talebiniz üzerine şifre sıfırlama linki aşağıda belirtilmiştir. Linke tıklayarak yeni şifrenizi belirleyeceğiniz sayfaya gidebilirisiniz.</p>
                            <p><a href="https://www.aldiahair.com/admin/newpass.php?renewpass=true&token='.$token_code.'">Şifreyi Sıfırla</a></p>
                        </body>
                        </html>';
            
            $mail->IsHTML(true);


            if($mail->Send())
            {
                header('Location:../login.php?status=mailsent');
            }
            else {
                    header('Location:../login.php?status=mailsentfail');
            }

		}else{
			header('Location:../login.php?status=repassfail');
		}
	}
}

/* Renew Password */
if(isset($_POST['newpass'])){
	$token = $_POST['user_token'];
	if($_POST['pass']!== $_POST['pass_control']){
		header("Location:../newpass.php?token=$token&status=notequal");
	}else{
	$query=$db->prepare("UPDATE users SET
	user_pass=:pass,
	user_token=:token WHERE id={$_POST['id']}");
	$update=$query->execute(array(
	'pass'=>sha1(md5($_POST['pass_control'])),
	'token'=>md5(uniqid())
	));

	if($update){
		header('Location:../login.php?status=passchanged');
	}else{
		header('Location:../login.php?status=passchangefail');
	}
	}
}

/* Profile Picture Update */
if(isset($_POST['picupdate'])){
	$allowed_ext=array("jpg","png","gif");
	$ext=strtolower(substr($_FILES['user_pic']['name'],strpos($_FILES['user_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Sadece JPG, PNG ve GIF formatı yükleyebilirsiniz.";
		$_SESSION['icon'] = "error";
		header('Location:../profilesetup.php');
		exit();
	}

	if($_FILES['user_pic']['size']>1048576){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemeye çalıştığınız resim en fazla 1mb. boyutunda olmalıdır.";
		$_SESSION['icon'] = "error";
		header('Location:../profilesetup.php');
		exit();
	}

		$uploads_dir='../img';
		@$tmp_name=$_FILES['user_pic']["tmp_name"];
		@$name=$_FILES['user_pic']["name"];
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,3)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$update_prof=$db->prepare("UPDATE users SET
		user_pic=:pic
		WHERE id={$_POST['id']}");

		$update=$update_prof->execute(array(
		'pic'    =>$refimgyol));

		if($update){
			$unlink=$_POST['unlink'];
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Profil resmi başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			unlink("../$unlink");
			header("Location:../profilesetup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Profil resmi güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../profilesetup.php");
		}
}

/* Profile Info Update */
if(isset($_POST['infoupdate'])){
	$update_prof=$db->prepare("UPDATE users SET
		user_name=:name,
		user_mail=:mail
		WHERE id={$_POST['user_id']}");

		$update=$update_prof->execute(array(
		'name' => htmlspecialchars(trim($_POST['user_name'])),
		'mail'    => htmlspecialchars(trim($_POST['user_mail']))));

		if($update){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Bilgileriniz başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../profilesetup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Bilgileriniz güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../profilesetup.php");
		}
}

/* Add Slider */
if(isset($_POST['add_slider'])){
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['slider_pic']['name'],strpos($_FILES['slider_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header('Location:../add-slider.php');
		exit();
	}
	if($_FILES['slider_pic']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header('Location:../add-slider.php');
		exit();
	}else{
		$uploads_dir='../../img/slider';
		@$tmp_name=$_FILES['slider_pic']["tmp_name"];
		@$name=$_FILES['slider_pic']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$add_image=$db->prepare("INSERT INTO slider SET
		up_title_tr=:up_title_tr,
		up_title_en=:up_title_en,
		up_title_ger=:up_title_ger,
		up_title_fr=:up_title_fr,
		up_title_ar=:up_title_ar,
		title_tr=:title_tr,
		title_en=:title_en,
		title_ger=:title_ger,
		title_fr=:title_fr,
		title_ar=:title_ar,
		text_tr=:text_tr,
		text_en=:text_en,
		text_ger=:text_ger,
		text_fr=:text_fr,
		text_ar=:text_ar,
		slider_link=:link,
		pic_url=:pic");

		$add_service=$add_image->execute(array(
		"up_title_tr" => trim($_POST["up_title_tr"]),
		"up_title_en" => trim($_POST["up_title_en"]),
		"up_title_ger" => trim($_POST["up_title_ger"]),
		"up_title_fr" => trim($_POST["up_title_fr"]),
		"up_title_ar" => trim($_POST["up_title_ar"]),
		"title_tr" => trim($_POST["title_tr"]),
		"title_en" => trim($_POST["title_en"]),
		"title_ger" => trim($_POST["title_ger"]),
		"title_fr" => trim($_POST["title_fr"]),
		"title_ar" => trim($_POST["title_ar"]),
		"text_tr"  => trim($_POST["text_tr"]),
		"text_en"  => trim($_POST["text_en"]),
		"text_ger"  => trim($_POST["text_ger"]),
		"text_fr"  => trim($_POST["text_fr"]),
		"text_ar"  => trim($_POST["text_ar"]),
		"link"  => trim($_POST["slider_link"]),
		'pic'      => $refimgyol));

		if($add_service){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Slider başarılı bir şekilde eklenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../sliderlist.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Slider eklenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header('Location:../sliderlist.php');
		}
	}
}

/* Slider Rank */
if(isset($_POST["data"])){
	parse_str($_POST["data"], $siralama);
	$rank = $siralama["rank"];
	foreach($rank as $key => $id){
		
		$query=$db->prepare("UPDATE slider SET slider_rank=:rank WHERE id=:id");
		$update=$query->execute(array("rank" => $key, "id" => $id));
	}
}

/* Slider Picture Update */
if(isset($_POST['update_slider_pic'])){
	
	$slider_id=$_POST['slider_id'];
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['slider_pic']['name'],strpos($_FILES['slider_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-slider.php?id=$slider_id");
		exit();
	}
	if($_FILES['slider_pic']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-slider.php?id=$slider_id");
		exit();
	}else{
		$uploads_dir='../../img/slider';
		@$tmp_name=$_FILES['slider_pic']["tmp_name"];
		@$name=$_FILES['slider_pic']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_slider_pic=$db->prepare("UPDATE slider SET
		pic_url=:pic WHERE id={$slider_id}");

		$updated=$edit_slider_pic->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["slider_pic"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Slider resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../edit-slider.php?id=$slider_id");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Slider resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../edit-slider.php?id=$slider_id");
		}
	}
}

/* Slider Content Update */
if(isset($_POST['edit_slider'])){
	
	$slider_id=$_POST['slider_id'];
	
	$edit_slider=$db->prepare("UPDATE slider SET
	up_title_tr=:up_title_tr,
	up_title_en=:up_title_en,
	up_title_ger=:up_title_ger,
	up_title_fr=:up_title_fr,
	up_title_ar=:up_title_ar,
	title_tr=:title_tr,
	title_en=:title_en,
	title_ger=:title_ger,
	title_fr=:title_fr,
	title_ar=:title_ar,
	text_tr=:text_tr,
	text_en=:text_en,
	text_ger=:text_ger,
	text_fr=:text_fr,
	text_ar=:text_ar,
	slider_link=:link
	WHERE id={$slider_id}");

	$updated=$edit_slider->execute(array(
	"up_title_tr"  => trim($_POST["up_title_tr"]),
	"up_title_en"  => trim($_POST["up_title_en"]),
	"up_title_ger"  => trim($_POST["up_title_ger"]),
	"up_title_fr"  => trim($_POST["up_title_fr"]),
	"up_title_ar"  => trim($_POST["up_title_ar"]),
	"title_tr"  => trim($_POST["title_tr"]),
	"title_en"  => trim($_POST["title_en"]),
	"title_ger"  => trim($_POST["title_ger"]),
	"title_fr"  => trim($_POST["title_fr"]),
	"title_ar"  => trim($_POST["title_ar"]),
	"text_tr"   => trim($_POST["text_tr"]),
	"text_en"   => trim($_POST["text_en"]),
	"text_ger"   => trim($_POST["text_ger"]),
	"text_fr"   => trim($_POST["text_fr"]),
	"text_ar"   => trim($_POST["text_ar"]),
	"link"		=> trim($_POST["slider_link"])
	));

	if($updated){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Slider başarılı bir şekilde güncellenmiştir.";
		$_SESSION['icon'] = "success";
		header("Location:../edit-slider.php?id=$slider_id");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Slider güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-slider.php?id=$slider_id");
	}
}

/* Delete Slider */
if(isset($_POST["delete_slider"])){
	$delete_qry=$db->prepare("DELETE FROM slider WHERE id=:id");
	$delete_slider=$delete_qry->execute(array('id'=>$_POST['delete_id']));
	if($delete_slider){
		$unlink=$_POST["unlink"];
		unlink("../../$unlink");
	}
}

/* Slider Down Box1 */
if(isset($_POST['card_update1'])){
	
	$edit_card=$db->prepare("UPDATE slider_down SET
	title_tr=:title_tr,
	title_en=:title_en,
	title_ger=:title_ger,
	title_fr=:title_fr,
	title_ar=:title_ar,
	icon=:icon,
	box_link=:box_link
	WHERE id=1");

	$updated=$edit_card->execute(array(
	"title_tr"  => trim($_POST["title_tr"]),
	"title_en"  => trim($_POST["title_en"]),
	"title_ger" => trim($_POST["title_ger"]),
	"title_fr"  => trim($_POST["title_fr"]),
	"title_ar"  => trim($_POST["title_ar"]),
	"icon"  	=> trim($_POST["icon"]),
	"box_link"  => trim($_POST["box_link"])
	));

	if($updated){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Öne Çıkarılan Hizmet başarılı bir şekilde güncellendi.";
		$_SESSION['icon'] = "success";
		header("Location:../slider-down.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Öne Çıkarılan Hizmet güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../slider-down.php");
	}
}

/* Slider Down Box2 */
if(isset($_POST['card_update2'])){
	
	$edit_card=$db->prepare("UPDATE slider_down SET
	title_tr=:title_tr,
	title_en=:title_en,
	title_ger=:title_ger,
	title_fr=:title_fr,
	title_ar=:title_ar,
	icon=:icon,
	box_link=:box_link
	WHERE id=2");

	$updated=$edit_card->execute(array(
	"title_tr"  => trim($_POST["title_tr"]),
	"title_en"  => trim($_POST["title_en"]),
	"title_ger" => trim($_POST["title_ger"]),
	"title_fr"  => trim($_POST["title_fr"]),
	"title_ar"  => trim($_POST["title_ar"]),
	"icon"  	=> trim($_POST["icon"]),
	"box_link"  => trim($_POST["box_link"])
	));

	if($updated){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Öne Çıkarılan Hizmet başarılı bir şekilde güncellendi.";
		$_SESSION['icon'] = "success";
		header("Location:../slider-down.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Öne Çıkarılan Hizmet güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../slider-down.php");
	}
}

/* Slider Down Box 3 */
if(isset($_POST['card_update3'])){
	
	$edit_card=$db->prepare("UPDATE slider_down SET
	title_tr=:title_tr,
	title_en=:title_en,
	title_ger=:title_ger,
	title_fr=:title_fr,
	title_ar=:title_ar,
	icon=:icon,
	box_link=:box_link
	WHERE id=3");

	$updated=$edit_card->execute(array(
	"title_tr"  => trim($_POST["title_tr"]),
	"title_en"  => trim($_POST["title_en"]),
	"title_ger" => trim($_POST["title_ger"]),
	"title_fr"  => trim($_POST["title_fr"]),
	"title_ar"  => trim($_POST["title_ar"]),
	"icon"  	=> trim($_POST["icon"]),
	"box_link"  => trim($_POST["box_link"])
	));

	if($updated){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Öne Çıkarılan Hizmet başarılı bir şekilde güncellendi.";
		$_SESSION['icon'] = "success";
		header("Location:../slider-down.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Öne Çıkarılan Hizmet güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../slider-down.php");
	}
}

/* Slider Down Box 4 */
if(isset($_POST['card_update4'])){
	
	$edit_card=$db->prepare("UPDATE slider_down SET
	title_tr=:title_tr,
	title_en=:title_en,
	title_ger=:title_ger,
	title_fr=:title_fr,
	title_ar=:title_ar,
	icon=:icon,
	box_link=:box_link
	WHERE id=4");

	$updated=$edit_card->execute(array(
	"title_tr"  => trim($_POST["title_tr"]),
	"title_en"  => trim($_POST["title_en"]),
	"title_ger" => trim($_POST["title_ger"]),
	"title_fr"  => trim($_POST["title_fr"]),
	"title_ar"  => trim($_POST["title_ar"]),
	"icon"  	=> trim($_POST["icon"]),
	"box_link"  => trim($_POST["box_link"])
	));

	if($updated){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Öne Çıkarılan Hizmet başarılı bir şekilde güncellendi.";
		$_SESSION['icon'] = "success";
		header("Location:../slider-down.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Öne Çıkarılan Hizmet güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../slider-down.php");
	}
}

/* About Page Cover */
if(isset($_POST['about_page_picture_update'])){
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['about_bg']['name'],strpos($_FILES['about_bg']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../about-bg-setup.php");
		exit();
	}
	if($_FILES['about_bg']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../about-bg-setup.php");
		exit();
	}else{
		$uploads_dir='../../img/bg';
		@$tmp_name=$_FILES['about_bg']["tmp_name"];
		@$name=$_FILES['about_bg']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_service_bg=$db->prepare("UPDATE about_bg SET
		pic_url=:pic WHERE id=0");

		$updated=$edit_service_bg->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["unlink"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sayfa kapak resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../about-bg-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sayfa kapak resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../about-bg-setup.php");
		}
	}
}

/* About Page Picture */
if(isset($_POST['about_pic'])){
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['pic_url']['name'],strpos($_FILES['pic_url']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../about-setup.php");
		exit();
	}
	if($_FILES['pic_url']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../about-setup.php");
		exit();
	}else{
		$uploads_dir='../../assets/images/about';
		@$tmp_name=$_FILES['pic_url']["tmp_name"];
		@$name=$_FILES['pic_url']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_service_bg=$db->prepare("UPDATE about SET
		pic_url=:pic WHERE id=0");

		$updated=$edit_service_bg->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["unlink"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sayfa kapak resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../about-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sayfa kapak resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../about-setup.php");
		}
	}
}

/* About Title */
if(isset($_POST["about_title_update"])){
	$title_edit=$db->prepare("UPDATE about SET
		title_tr=:title_tr,
		title_en=:title_en,
		title_ger=:title_ger,
		title_fr=:title_fr,
		title_ar=:title_ar WHERE id=0");
	
	$update=$title_edit->execute(array(
		"title_tr" => htmlspecialchars(trim($_POST["about_title_tr"])),
		"title_en" => htmlspecialchars(trim($_POST["about_title_en"])),
		"title_ger" => htmlspecialchars(trim($_POST["about_title_ger"])),
		"title_fr" => htmlspecialchars(trim($_POST["about_title_fr"])),
		"title_ar" => htmlspecialchars(trim($_POST["about_title_ar"]))
	));
	
	if($update){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Başlık başarılı bir şekilde güncellenmiştir.";
		$_SESSION['icon'] = "success";
		header("Location:../about-setup.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Başlık güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../about-setup.php");
	}
}

/* About Text */
if(isset($_POST["about_text_update"])){
	$text_edit=$db->prepare("UPDATE about SET
	text_tr=:text_tr,
	text_en=:text_en,
	text_ger=:text_ger,
	text_fr=:text_fr,
	text_ar=:text_ar WHERE id=0");
	
	$update=$text_edit->execute(array(
	"text_tr"  => $_POST["text_tr"],
	"text_en"  => $_POST["text_en"],
	"text_ger" => $_POST["text_ger"],
	"text_fr"  => $_POST["text_fr"],
	"text_ar"  => $_POST["text_ar"]
	));
	
	if($update){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Yazı başarılı bir şekilde güncellenmiştir.";
		$_SESSION['icon'] = "success";
		header("Location:../about-setup.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yazı güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../about-setup.php");
	}
}

/* Add Service */
if(isset($_POST['add_service'])){
	$allowed_ext=array("jpg","png","gif");
	$ext=strtolower(substr($_FILES['service_pic']['name'],strpos($_FILES['service_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header('Location:../add-service.php');
		exit();
	}
	if($_FILES['service_pic']['size']>1048576){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 1MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header('Location:../add-service.php');
		exit();
	}else{
		$uploads_dir='../../img/services';
		@$tmp_name=$_FILES['service_pic']["tmp_name"];
		@$name=$_FILES['service_pic']["name"];
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		/* Pic URL HOME */
		$allowed_ext=array("jpg","png","gif");
		$ext=strtolower(substr($_FILES['service_pic_home']['name'],strpos($_FILES['service_pic_home']['name'],'.')+1));
		if(in_array($ext, $allowed_ext)===false){
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
			$_SESSION['icon'] = "error";
			header('Location:../add-service.php');
			exit();
		}
		if($_FILES['service_pic_home']['size']>1048576){
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 1MB. üzerinde olmamalıdır.";
			$_SESSION['icon'] = "error";
			header('Location:../add-service.php');
			exit();
		}else{
			$uploads_dir='../../img/services';
			@$tmp_name=$_FILES['service_pic_home']["tmp_name"];
			@$name=$_FILES['service_pic_home']["name"];
			$benzersizsayi1=rand(20000,32000);
			$benzersizsayi2=rand(20000,32000);
			$benzersizad=$benzersizsayi1.$benzersizsayi2;
			$refimgyolhome=substr($uploads_dir,6)."/".$benzersizad.$name;
			@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$add_image=$db->prepare("INSERT INTO services SET
		service_title_tr=:title_tr,
		service_title_en=:title_en,
		service_title_ger=:title_ger,
		service_title_fr=:title_fr,
		service_title_ar=:title_ar,
		service_text_tr=:text_tr,
		service_text_en=:text_en,
		service_text_ger=:text_ger,
		service_text_fr=:text_fr,
		service_text_ar=:text_ar,
		pic_url_home=:pic_home,
		pic_url=:pic");

		$add_service=$add_image->execute(array(
		"title_tr"  => htmlspecialchars(trim($_POST["service_title_tr"])),
		"title_en"  => htmlspecialchars(trim($_POST["service_title_en"])),
		"title_ger" => htmlspecialchars(trim($_POST["service_title_ger"])),
		"title_fr" => htmlspecialchars(trim($_POST["service_title_fr"])),
		"title_ar"  => htmlspecialchars(trim($_POST["service_title_ar"])),
		"text_tr"   => $_POST["service_text_tr"],
		"text_en"   => $_POST["service_text_en"],
		"text_ger"  => $_POST["service_text_ger"],
		"text_fr"  => $_POST["service_text_fr"],
		"text_ar"   => $_POST["service_text_ar"],
		"pic_home"  => $refimgyolhome,
		"pic"    	=> $refimgyol));

		if($add_service){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Hizmet başarılı bir şekilde eklenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../serviceslist.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Hizmet eklenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header('Location:../serviceslist.php');
		}
	  }
	}
}

/* Service Home Picture Update */
if(isset($_POST['update_service_home_pic'])){
	
	$service_id=$_POST['service_id'];
	
	$allowed_ext=array("jpg","png","gif");
	$ext=strtolower(substr($_FILES['service_home_pic']['name'],strpos($_FILES['service_home_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-service.php?id=$service_id");
		exit();
	}
	if($_FILES['service_home_pic']['size']>1048576){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 1MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-service.php?id=$service_id");
		exit();
	}else{
		$uploads_dir='../../img/services';
		@$tmp_name=$_FILES['service_home_pic']["tmp_name"];
		@$name=$_FILES['service_home_pic']["name"];
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_service_pic=$db->prepare("UPDATE services SET
		pic_url_home=:pic WHERE id={$service_id}");

		$updated=$edit_service_pic->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["service_home_pic"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Hizmet kapak resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../edit-service.php?id=$service_id");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Hizmet kapak resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../edit-service.php?id=$service_id");
		}
	}
}

/* Service Picture Update */
if(isset($_POST['update_service_pic'])){
	
	$service_id=$_POST['service_id'];
	
	$allowed_ext=array("jpg","png","gif");
	$ext=strtolower(substr($_FILES['service_pic']['name'],strpos($_FILES['service_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-service.php?id=$service_id");
		exit();
	}
	if($_FILES['service_pic']['size']>1048576){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 1MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../edit-service.php?id=$service_id");
		exit();
	}else{
		$uploads_dir='../../img/services';
		@$tmp_name=$_FILES['service_pic']["tmp_name"];
		@$name=$_FILES['service_pic']["name"];
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_service_pic=$db->prepare("UPDATE services SET
		pic_url=:pic WHERE id={$service_id}");

		$updated=$edit_service_pic->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["service_pic"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Hizmet kapak resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../edit-service.php?id=$service_id");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Hizmet kapak resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../edit-service.php?id=$service_id");
		}
	}
}

/* Service Update */
if(isset($_POST['edit_service'])){
	
	$service_id=$_POST['service_id'];
	
	$edit_service=$db->prepare("UPDATE services SET
	service_title_tr=:title_tr,
	service_title_en=:title_en,
	service_title_ger=:title_ger,
	service_title_fr=:title_fr,
	service_title_ar=:title_ar,
	service_text_tr=:text_tr,
	service_text_en=:text_en,
	service_text_ger=:text_ger,
	service_text_fr=:text_fr,
	service_text_ar=:text_ar WHERE id={$service_id}");

	$updated=$edit_service->execute(array(
	"title_tr"  => htmlspecialchars(trim($_POST["service_title_tr"])),
	"title_en"  => htmlspecialchars(trim($_POST["service_title_en"])),
	"title_ger" => htmlspecialchars(trim($_POST["service_title_ger"])),
	"title_fr" => htmlspecialchars(trim($_POST["service_title_fr"])),
	"title_ar"  => htmlspecialchars(trim($_POST["service_title_ar"])),
	"text_tr"   => $_POST["service_text_tr"],
	"text_en"   => $_POST["service_text_en"],
	"text_ger"  => $_POST["service_text_ger"],
	"text_fr"  => $_POST["service_text_fr"],
	"text_ar"   => $_POST["service_text_ar"]));

	if($updated){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Hizmet başarılı bir şekilde güncellenmiştir.";
		$_SESSION['icon'] = "success";
		header("Location:../edit-service.php?id=$service_id");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Hizmet güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../service-bg-setup.php");
	}
}

/* Services Page Cover Update */
if(isset($_POST['service_page_picture_update'])){
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['services_bg']['name'],strpos($_FILES['services_bg']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../service-bg-setup.php");
		exit();
	}
	if($_FILES['services_bg']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../service-bg-setup.php");
		exit();
	}else{
		$uploads_dir='../../img/bg';
		@$tmp_name=$_FILES['services_bg']["tmp_name"];
		@$name=$_FILES['services_bg']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_service_bg=$db->prepare("UPDATE services_bg SET
		pic_url=:pic WHERE id=0");

		$updated=$edit_service_bg->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["unlink"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sayfa kapak resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../service-bg-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sayfa kapak resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../service-bg-setup.php");
		}
	}
}

/* Service Rank */
if(isset($_POST["data"])){
	parse_str($_POST["data"], $siralama);
	$rank = $siralama["rank"];
	foreach($rank as $key => $id){
		
		$query=$db->prepare("UPDATE services SET service_rank=:rank WHERE id=:id");
		$update=$query->execute(array("rank" => $key, "id" => $id));
	}
}

/* Delete Service */
if(isset($_POST["delete_service"])){
	$delete_qry=$db->prepare("DELETE FROM services WHERE id=:id");
	$delete_service=$delete_qry->execute(array('id'=>$_POST['delete_id']));
	if($delete_service){
		$unlink=$_POST["unlink"];
		$unlink2=$_POST["unlink2"];
		unlink("../../$unlink");
		unlink("../../$unlink2");
	}
}

/* Home Form Picture */
if(isset($_POST['update_home_form_pic'])){
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['home_form_pic']['name'],strpos($_FILES['home_form_pic']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../home-form-setup.php");
		exit();
	}
	if($_FILES['home_form_pic']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../home-form-setup.php");
		exit();
	}else{
		$uploads_dir='../../img';
		@$tmp_name=$_FILES['home_form_pic']["tmp_name"];
		@$name=$_FILES['home_form_pic']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_service_bg=$db->prepare("UPDATE home_form SET
		pic_url=:pic WHERE id=0");

		$updated=$edit_service_bg->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["unlink"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Form resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../home-form-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Form resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../home-form-setup.php");
		}
	}
}

/* Home Contact Main Title */
if(isset($_POST["home_form_main_title_update"])){
	$edit_form_title=$db->prepare("UPDATE home_form SET
	main_title_tr=:main_title_tr,
	main_title_en=:main_title_en,
	main_title_ger=:main_title_ger,
	main_title_fr=:main_title_fr,
	main_title_ar=:main_title_ar WHERE id=0");
	
	$update=$edit_form_title->execute(array(
	"main_title_tr"  => htmlspecialchars(trim($_POST["main_title_tr"])),
	"main_title_en"  => htmlspecialchars(trim($_POST["main_title_en"])),
	"main_title_ger" => htmlspecialchars(trim($_POST["main_title_ger"])),
	"main_title_fr"  => htmlspecialchars(trim($_POST["main_title_fr"])),
	"main_title_ar"  => htmlspecialchars(trim($_POST["main_title_ar"]))
	));
	
	if($update){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Form ana başlık başarılı bir şekilde güncellenmiştir.";
		$_SESSION['icon'] = "success";
		header("Location:../home-form-setup.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Form ana başlık güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../home-form-setup.php");
	}
}

/* Home Contact Sub Text */
if(isset($_POST["home_form_sub_title_update"])){
	$edit_form_title=$db->prepare("UPDATE home_form SET
	sub_title_tr=:sub_title_tr,
	sub_title_en=:sub_title_en,
	sub_title_ger=:sub_title_ger,
	sub_title_fr=:sub_title_fr,
	sub_title_ar=:sub_title_ar WHERE id=0");
	
	$update=$edit_form_title->execute(array(
	"sub_title_tr"  => htmlspecialchars(trim($_POST["sub_title_tr"])),
	"sub_title_en"  => htmlspecialchars(trim($_POST["sub_title_en"])),
	"sub_title_ger" => htmlspecialchars(trim($_POST["sub_title_ger"])),
	"sub_title_fr"  => htmlspecialchars(trim($_POST["sub_title_fr"])),
	"sub_title_ar"  => htmlspecialchars(trim($_POST["sub_title_ar"]))
	));
	
	if($update){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Form alt başlık başarılı bir şekilde güncellenmiştir.";
		$_SESSION['icon'] = "success";
		header("Location:../home-form-setup.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Form alt başlık güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../home-form-setup.php");
	}
}

/* Gallery Page Cover */
if(isset($_POST['gallery_page_picture_update'])){
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['gallery_bg']['name'],strpos($_FILES['gallery_bg']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../gallery-bg-setup.php");
		exit();
	}
	if($_FILES['gallery_bg']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../gallery-bg-setup.php");
		exit();
	}else{
		$uploads_dir='../../img/bg';
		@$tmp_name=$_FILES['gallery_bg']["tmp_name"];
		@$name=$_FILES['gallery_bg']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_service_bg=$db->prepare("UPDATE gallery_bg SET
		pic_url=:pic WHERE id=0");

		$updated=$edit_service_bg->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["unlink"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sayfa kapak resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../gallery-bg-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sayfa kapak resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../gallery-bg-setup.php");
		}
	}
}

/* Gallery Picture Delete */
if(isset($_POST["delete_galleryimages"]))
{
	foreach($_POST["delete_gallery"] as $image){

		$get_imgurl=$db->prepare("SELECT * FROM gallery WHERE id=$image");
		$get_imgurl->execute();

		$delete_qry=$db->prepare("DELETE FROM gallery WHERE id=$image");
		$delete_qry->execute();

		while($img_url=$get_imgurl->fetch(PDO::FETCH_ASSOC)){
			$unlink = $img_url["pic_url"];
			unlink("../../$unlink");
		}
	}

	if($delete_qry){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Resim(ler) başarılı bir şekilde silindi.";
			$_SESSION['icon'] = "success";
			header("Location:../gallery-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Resim(ler) silinirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../gallery-setup.php");
		}

}

/* Contact Page Cover */
if(isset($_POST['contact_page_picture_update'])){
	
	$allowed_ext=array("jpg","png","gif");
	
	$ext=strtolower(substr($_FILES['contact_bg']['name'],strpos($_FILES['contact_bg']['name'],'.')+1));
	if(in_array($ext, $allowed_ext)===false){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resim JPG, PNG veya GIF formatında olmalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../about-bg-setup.php");
		exit();
	}
	if($_FILES['contact_bg']['size']>2097152){
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Yüklemek istediğiniz resimin boyutu 2MB. üzerinde olmamalıdır.";
		$_SESSION['icon'] = "error";
		header("Location:../about-bg-setup.php");
		exit();
	}else{
		$uploads_dir='../../img/bg';
		@$tmp_name=$_FILES['contact_bg']["tmp_name"];
		@$name=$_FILES['contact_bg']["name"];
		$name=preg_replace("/[^a-zA-Z0-9.]/", "", $name);
		$benzersizsayi1=rand(20000,32000);
		$benzersizsayi2=rand(20000,32000);
		$benzersizad=$benzersizsayi1.$benzersizsayi2;
		$refimgyol=substr($uploads_dir,6)."/".$benzersizad.$name;
		@move_uploaded_file($tmp_name,"$uploads_dir/$benzersizad$name");

		$edit_service_bg=$db->prepare("UPDATE contact_bg SET
		pic_url=:pic WHERE id=0");

		$updated=$edit_service_bg->execute(array(
		'pic'    => $refimgyol));
		
		$unlink=$_POST["unlink"];

		if($updated){
			unlink("../../$unlink");
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sayfa kapak resmi başarılı bir şekilde güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../contact-bg-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sayfa kapak resmi güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
			$_SESSION['icon'] = "error";
			header("Location:../contact-bg-setup.php");
		}
	}
}

/* Contact Form Title */
if(isset($_POST["form_title_update"])){
	$edit_form_title=$db->prepare("UPDATE form SET
	title_tr=:title_tr,
	title_en=:title_en,
	title_ger=:title_ger,
	title_fr=:title_fr,
	title_ar=:title_ar WHERE id=0");
	
	$update=$edit_form_title->execute(array(
	"title_tr"  => htmlspecialchars(trim($_POST["title_tr"])),
	"title_en"  => htmlspecialchars(trim($_POST["title_en"])),
	"title_ger" => htmlspecialchars(trim($_POST["title_ger"])),
	"title_fr" => htmlspecialchars(trim($_POST["title_fr"])),
	"title_ar"  => htmlspecialchars(trim($_POST["title_ar"]))
	));
	
	if($update){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Form başlık başarılı bir şekilde güncellenmiştir.";
		$_SESSION['icon'] = "success";
		header("Location:../form-setup.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Form başlık güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../form-setup.php");
	}
}

/* Contact Form Text */
if(isset($_POST["form_short_text_update"])){
	$edit_form_title=$db->prepare("UPDATE form SET
	text_tr=:text_tr,
	text_en=:text_en,
	text_ger=:text_ger,
	text_fr=:text_fr,
	text_ar=:text_ar WHERE id=0");
	
	$update=$edit_form_title->execute(array(
	"text_tr"  => htmlspecialchars(trim($_POST["text_tr"])),
	"text_en"  => htmlspecialchars(trim($_POST["text_en"])),
	"text_ger" => htmlspecialchars(trim($_POST["text_ger"])),
	"text_fr" => htmlspecialchars(trim($_POST["text_fr"])),
	"text_ar"  => htmlspecialchars(trim($_POST["text_ar"]))
	));
	
	if($update){
		$_SESSION['title'] = "İşlem Başarılı";
		$_SESSION['status'] = "Form başlık başarılı bir şekilde güncellenmiştir.";
		$_SESSION['icon'] = "success";
		header("Location:../form-setup.php");
	}else{
		$_SESSION['title'] = "Hata!";
		$_SESSION['status'] = "Form başlık güncellenirken bir hata oluştu. Daha sonra tekrar deneyin veya info@excess.web.tr adresine bildirin.";
		$_SESSION['icon'] = "error";
		header("Location:../form-setup.php");
	}
}

/* SEO Update */
/* Site Title */
if(isset($_POST['title_update'])){
	$update_title=$db->prepare("UPDATE seo_setup SET
		title_tr=:title_tr,
		title_en=:title_en,
		title_ger=:title_ger,
		title_fr=:title_fr,
		title_ar=:title_ar
		WHERE id=0");

		$update=$update_title->execute(array(
		'title_tr' 	=> htmlspecialchars(trim($_POST['title_tr'])),
		'title_en'  => htmlspecialchars(trim($_POST['title_en'])),
		'title_ger'  => htmlspecialchars(trim($_POST['title_ger'])),
		'title_fr'  => htmlspecialchars(trim($_POST['title_fr'])),
		'title_ar'  => htmlspecialchars(trim($_POST['title_ar']))
		
		));

		if($update){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sayfa Başlığı başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../seo-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sayfa Başlığı güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../seo-setup.php");
		}
} 

/* Site Description Update */
if(isset($_POST['desc_update'])){
	$update_desc=$db->prepare("UPDATE seo_setup SET
		desc_tr=:desc_tr,
		desc_en=:desc_en,
		desc_ger=:desc_ger,
		desc_fr=:desc_fr,
		desc_ar=:desc_ar
		WHERE id=0");

		$update=$update_desc->execute(array(
		'desc_tr' 	=> htmlspecialchars(trim($_POST['desc_tr'])),
		'desc_en'  => htmlspecialchars(trim($_POST['desc_en'])),
		'desc_ger'  => htmlspecialchars(trim($_POST['desc_ger'])),
		'desc_fr'  => htmlspecialchars(trim($_POST['desc_fr'])),
		'desc_ar'  => htmlspecialchars(trim($_POST['desc_ar']))
		
		));

		if($update){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sayfa Açıklaması başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../seo-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sayfa Açıklaması güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../seo-setup.php");
		}
}

/* Site Keywords Update */
if(isset($_POST['keyw_update'])){
	$update_keyw=$db->prepare("UPDATE seo_setup SET
		keyw_tr=:keyw_tr,
		keyw_en=:keyw_en,
		keyw_ger=:keyw_ger,
		keyw_fr=:keyw_fr,
		keyw_ar=:keyw_ar
		WHERE id=0");

		$update=$update_keyw->execute(array(
		'keyw_tr'  => htmlspecialchars(trim($_POST['keyw_tr'])),
		'keyw_en'  => htmlspecialchars(trim($_POST['keyw_en'])),
		'keyw_ger' => htmlspecialchars(trim($_POST['keyw_ger'])),
		'keyw_fr' => htmlspecialchars(trim($_POST['keyw_fr'])),
		'keyw_ar'  => htmlspecialchars(trim($_POST['keyw_ar']))
		
		));

		if($update){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sayfa Keywords başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../seo-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sayfa Keywords güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../seo-setup.php");
		}
}

/* Site Footer Short About Update */
if(isset($_POST['short_about_update'])){
	$update_about=$db->prepare("UPDATE seo_setup SET
		short_about_tr=:short_tr,
		short_about_en=:short_en,
		short_about_ger=:short_ger,
		short_about_fr=:short_fr,
		short_about_ar=:short_ar
		WHERE id=0");

		$update=$update_about->execute(array(
		'short_tr'  => htmlspecialchars(trim($_POST['short_about_tr'])),
		'short_en'  => htmlspecialchars(trim($_POST['short_about_en'])),
		'short_ger' => htmlspecialchars(trim($_POST['short_about_ger'])),
		'short_fr' => htmlspecialchars(trim($_POST['short_about_fr'])),
		'short_ar'  => htmlspecialchars(trim($_POST['short_about_ar']))
		
		));

		if($update){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Kısa hakkımızda yazısı başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../seo-setup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Kısa hakkımızda yazısı güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../seo-setup.php");
		}
}

/* Contact Information Update */
if(isset($_POST["contact_update"])){
	$update_contact=$db->prepare("UPDATE contact_settings SET
		phone=:phone,
		whatsapp=:whatsapp,
		mail=:mail,
		monfri=:monfri,
		satsun=:satsun,
		address=:address,
		google_map=:google_map WHERE id=0");
	
	$contact_updated=$update_contact->execute(array(
		'phone' 	 => htmlspecialchars(trim($_POST['phone'])),
		'whatsapp'   => htmlspecialchars(trim($_POST['whatsapp'])),
		'mail'  	 => htmlspecialchars(trim($_POST['mail'])),
		'monfri'  	 => htmlspecialchars(trim($_POST['monfri'])),
		'satsun'  	 => htmlspecialchars(trim($_POST['satsun'])),
		'address'  	 => htmlspecialchars(trim($_POST['address'])),
		'google_map' => $_POST["google_map"]
	));
	
	if($contact_updated){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sayfa iletişim bilgileri başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../contactsetup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sayfa iletişim bilgileri güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../contactsetup.php");
		}
}

/* Social Media Update */
if(isset($_POST["media_update"])){
	$update_media=$db->prepare("UPDATE social_media SET
		facebook=:facebook,
		instagram=:instagram,
		twitter=:twitter,
		youtube=:youtube
		WHERE id=0");
	
	$media_updated=$update_media->execute(array(
		'facebook' 	=> htmlspecialchars(trim($_POST['facebook'])),
		'instagram' => htmlspecialchars(trim($_POST['instagram'])),
		'twitter' => htmlspecialchars(trim($_POST['twitter'])),
		'youtube'  	=> htmlspecialchars(trim($_POST['youtube']))
	));
	
	if($media_updated){
			$_SESSION['title'] = "İşlem Başarılı";
			$_SESSION['status'] = "Sosyal Medya bilgileri başarıyla güncellenmiştir.";
			$_SESSION['icon'] = "success";
			header("Location:../socialmediasetup.php");
		}else{
			$_SESSION['title'] = "Hata!";
			$_SESSION['status'] = "Sosyal Medya bilgileri güncellenirken bir hata oluştu.";
			$_SESSION['icon'] = "error";
			header("Location:../socialmediasetup.php");
		}
}
?>